config :
  path : config.json
verbose : true
cache_duration: 3600
logger:
  stream : true
  level: 10
network :
  address: '0.0.0.0'
  port : 53
redis :
  host : 'localhost'
  port : 6379
  password : ''
  db : 0